### PR TITLE
VA-1899 recommended endpoints

### PR DESCRIPTION
**Pull request by anthonycr**
#### Ticket
[VA-1899](https://vimean.atlassian.net/browse/VA-1899)

#### Ticket Summary
We want to get the recommended endpoints for users and channels from the API.

#### Implementation Summary
Added the user and channel recommendation connections to the ConnectionCollection

### CODE REVIEW

**Comment by anthonycr** [comment]
[ ] wait for [this PR to be merged](https://github.com/vimeo/vimeo-networking-java/pull/139)

**Comment by howardrigberg** [comment]
Let me know when you are ready for me to review.

**Comment by anthonycr** [comment]
@howardrigberg you can review this now

**Comment by howardrigberg** [comment]
:shipit:

**Pull request merged**
