### PR TITLE
Issue template

### PR DESCRIPTION
**Pull request by kevinzetterstrom**
#### Ticket Summary
Adding an issue template and moving the contributing file. @alfiehanssen @kvenn what do y'all think of the issue template?

### CODE REVIEW

**Comment by alfiehanssen** [comment]
Love it :tangerine:

**Comment by kvenn** [comment]
Bomb diggity

We should probably hook iOS up with this, or maybe make a ticket for them since they're probably swamped.

**Comment by kevinzetterstrom** [comment]
Glad you guys like it. I will confirm it works as expected after I merge after which I will take care of adding this to all our public mobile repos, iOS included.

**Comment by Dashron** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Pull request merged**
